repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: style
    name: Check Style
    entry: bash scripts/check_style_pre_commit
    types: [python]
    language: system
    always_run: true
    pass_filenames: false
  - id: security
    name: Check Security
    entry: bash scripts/check_security_pre_commit
    types: [python]
    language: system
    always_run: true
    pass_filenames: false
