version: '3.8'

services:
  bayan_bot:
    image: bayan_bot:latest
    container_name: bayan_bot
    environment:
      - BOT_TOKEN=123
      - GROUP_CHAT_ID=-1
      - DATABASE_URL=sqlite:////opt/bot/CHAT_NAME.sqlite
    volumes:
      - /opt/CHAT_NAME:/opt/bot
    network_mode: bridge
