#!/bin/bash
set -e

poetry run black --target-version=py311 --check src/bayan_bot
poetry run isort --project=bayan_bot --check src/bayan_bot
poetry run mypy src/bayan_bot
poetry run flake8 --ignore=W503,T101,E501 src/bayan_bot
